version: '3.8'

services:
  # PHP Application Service
  app:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: sabimul-app
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - sabimul-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sabimul
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - VITE_SERVER=http://node:5173
    working_dir: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Node.js Service for Frontend Compilation
  node:
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    container_name: sabimul-node
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_URL=http://localhost:5173
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sabimul-network
    working_dir: /var/www/html
    tty: true
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.4
    container_name: sabimul-db
    restart: unless-stopped
    volumes:
      - sabimul-mysql-data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sabimul
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    networks:
      - sabimul-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sabimul-phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=100M
    networks:
      - sabimul-network

networks:
  sabimul-network:
    driver: bridge

volumes:
  sabimul-mysql-data: